### ISSUE TITLE
I want to use the eea.docker.jsnkins master and slave, but the plugin install failed a lot.

### ISSUE THREAD

**Issue by alexya** [eea/eea.docker.jenkins#6]
Hi, I have a Linux server and installed Swarm, then I configured the Jenkins master and slave. But after I input the key, and initial Jenkins master, I got many plug-ins failed. 

```
version: '3'

networks:
  default:
    driver: overlay

volumes:
  jenkins-master:
  jenkins-worker:

services:
  master:
    image: eeacms/jenkins-master:2.60.1
    ports:
    - "8000:8080"
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
    - jenkins-master:/var/jenkins_home

  worker:
    image: eeacms/jenkins-slave:3.4
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://master:8000"
      JENKINS_NAME: "worker"
      JENKINS_USER: "jenkins"
      JENKINS_PASS: "12345"
      JENKINS_RETRY: "10"
    volumes:
    - jenkins-worker:/var/jenkins_home/worker
```
And the errors like
![image](https://user-images.githubusercontent.com/2831220/30955176-4ff6d17c-a465-11e7-8523-7047157b65e3.png)

It seems that my worker always failed to connect to master, I am not sure if it is caused by that the master has not been initiated successfully. 
![image](https://user-images.githubusercontent.com/2831220/30955357-e75fff48-a465-11e7-9a3a-cdc598d609b0.png)

**Comment by avoinea** [comment]
@alexya Did you add a user called jenkins with password jenkins on master?

**Comment by alexya** [comment]
@avoinea 
I updated my .yml to the following, but the problem is still the same as before. 
```
version: '3'

networks:
  default:
    driver: overlay

volumes:
  jenkins-master:
  jenkins-worker:

services:
  master:
    image: eeacms/jenkins-master:2.60.1
    ports:
      - "8000:8080"
    environment:
      JAVA_OPTSr: "-Xmx2048m"
      JENKINS_NAME: "master"
      JENKINS_USER: "jenkins"
      JENKINS_PASS: "12345"
    volumes:
      - jenkins-master:/var/jenkins_home

  worker:
    image: eeacms/jenkins-slave:3.4
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://master:8080"
      JENKINS_NAME: "worker"
      JENKINS_USER: "jenkins"
      JENKINS_PASS: "12345"
      JENKINS_RETRY: "10"
    volumes:
      - jenkins-worker:/var/jenkins_home/worker
```
